name: Visual
on:
  pull_request:
    branches:
      - 'percy'
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn setup
          start: yarn start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
          # the entire command will automatically be prefixed with "npx"
          command-prefix: 'percy exec -- npx'
        env:
          # pass PERCY_TOKEN secret via environment variable
          PERCY_TOKEN: ${{ secrets.percy_token }}
